### ISSUE TITLE
Show a user friendly message to indicate `patch` utility is not found

### ISSUE THREAD

**Issue by WindSoilder** [speedyleion/gh-difftool#243]
Hi, When I'm trying to setup this tool with difft in my new machine.
I get an error message:
```
Error: No such file or directory (os error 2)
```
TBH it confused me for a while, I didn't know what happened until I see the following in README:
```
Requires
    ...
    The patch utility
```
I think it's good to show an error message like: `patch utility is not found, install it first`.

What do you think?

**Comment by speedyleion** [comment]
That sounds like a reasonable improvement

TBH i don't like the patch dependency. Not fond of calling out to a command line utility, but I couldn't find a crate to apply patches and it was a bit bigger lift than I wanted to dig into to implement.

**Comment by speedyleion** [comment]
The current error is
```
Error: No such file or directory (os error 2)
```

The code is using https://docs.rs/anyhow/latest/anyhow/
There is a [Context](https://docs.rs/anyhow/latest/anyhow/trait.Context.html) trait available from anyhow
I think adding a `context()` to https://github.com/speedyleion/gh-difftool/blob/3e36a9e2210a119330d300e632ef7b4ace4e3697/src/change_set.rs#L62 is a decent solution

```rust
        let mut child = cmd.spawn().context("Failed to spawn `patch`, is it installed?")?;
```

results in the following when `patch` isn't available
```
Error: Failed to spawn `patch`, is it installed?

Caused by:
    No such file or directory (os error 2)
```

This context will be displayed if there is any error spawning the patch utility. 

I'm not too concerned about this context being displayed for some other failure to spawn `patch` as the "is it installed?" doesn't say it's missing, it's just a hint. 
I think in these scenarios people will do `which patch` or similar just to be sure and report that with the error here on github.

I didn't want to look for the patch utility first, as it seems like a waste for most use cases as someone should only hit this on initial install, so why keep checking on every run.
If in the future there is a desire to make the error more robust I could potentially see looking for patch on failure, but I'm going to lean on [YAGNI](https://en.wikipedia.org/wiki/You_aren't_gonna_need_it) for not justifying that path at this time.

**Comment by speedyleion** [comment]
released in https://github.com/speedyleion/gh-difftool/releases/tag/v1.2.2
